sudo: false
dist: trusty
language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
before_install:
  - "npm i -g npm@latest"
install:
  - npm install
  - npm install -g codecov
before_script:
  - npm prune
script:
  - npm run cover
  - npm run build
  - codecov
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
